services:
  product-service-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: product-service-app
    container_name: product-service-app
    volumes:
      - .:/var/www/html:cached
      - ./vendor:/var/www/html/vendor:delegated
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=product-service-mysql
      - DB_PORT=3306
      - DB_DATABASE=product_service
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      product-service-mysql:
        condition: service_healthy
    entrypoint: /usr/local/bin/entrypoint.sh

  product-service-mysql:
    image: mysql:8.0
    container_name: product-service-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_service
    volumes:
      - product_service_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  product-service-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: product-service-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: product-service-mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      product-service-mysql:
        condition: service_healthy
    platform: linux/amd64

  product-service-nginx:
    image: nginx:latest
    container_name: product-service-nginx
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - product-service-app

volumes:
  product_service_db_data:
    driver: local
